# version: '3'
services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: panyu
      MYSQL_DATABASE: cloud-disk
      MYSQL_USER: panyu
      MYSQL_PASSWORD: panyu
    ports:
      - "3306:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
      - ./config/mysql/master/conf.d/:/etc/mysql/conf.d
    networks:
      - mysql-network
    restart: unless-stopped

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: panyu
      MYSQL_DATABASE: cloud-disk
      MYSQL_USER: panyu
      MYSQL_PASSWORD: panyu
    ports:
      - "3307:3306"
    volumes:
      - mysql-slave-data:/var/lib/mysql
      - ./config/mysql/slave/conf.d/:/etc/mysql/conf.d
    networks:
      - mysql-network   
    restart: unless-stopped
    depends_on:
      - mysql-master
      

  redis-data:
    image: redis:8.10.1-alpine
    container_name: redis-data
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data-volume:/data
      - ./cache/user.acl:/usr/local/etc/redis/user.acl:ro
    command: redis-server --aclfile /usr/local/etc/redis/user.acl --appendonly yes

volumes:
  mysql-master-data:
  mysql-slave-data:
  redis-data-volume:

networks:
  mysql-network:
    driver: bridge