// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package db

import (
	"context"
	"database/sql"
)

const createFile = `-- name: CreateFile :execresult
INSERT INTO files (
    file_sha1, file_name, file_size, file_addr )
     VALUES (?, ?, ?, ?)
`

type CreateFileParams struct {
	FileSha1 string `json:"file_sha1"`
	FileName string `json:"file_name"`
	FileSize int64  `json:"file_size"`
	FileAddr string `json:"file_addr"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFile,
		arg.FileSha1,
		arg.FileName,
		arg.FileSize,
		arg.FileAddr,
	)
}

const getFileById = `-- name: GetFileById :one
SELECT id, file_sha1, file_name, file_size, file_addr, status, create_at, update_at, extend, extend2 FROM files WHERE id = ? limit 1
`

func (q *Queries) GetFileById(ctx context.Context, id int64) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileById, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileSha1,
		&i.FileName,
		&i.FileSize,
		&i.FileAddr,
		&i.Status,
		&i.CreateAt,
		&i.UpdateAt,
		&i.Extend,
		&i.Extend2,
	)
	return i, err
}

const getFileBySha1 = `-- name: GetFileBySha1 :one
SELECT id, file_sha1, file_name, file_size, file_addr, status, create_at, update_at, extend, extend2 FROM files WHERE file_sha1 = ? limit 1
`

func (q *Queries) GetFileBySha1(ctx context.Context, fileSha1 string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileBySha1, fileSha1)
	var i File
	err := row.Scan(
		&i.ID,
		&i.FileSha1,
		&i.FileName,
		&i.FileSize,
		&i.FileAddr,
		&i.Status,
		&i.CreateAt,
		&i.UpdateAt,
		&i.Extend,
		&i.Extend2,
	)
	return i, err
}

const updateFile = `-- name: UpdateFile :execresult
UPDATE files SET 
    file_name = coalesce(?, file_name),
    file_size = coalesce(?, file_size),
    file_addr = coalesce(?, file_addr),
    status = coalesce(?, status),
    update_at = CURRENT_TIMESTAMP,
    extend = coalesce(?, extend),   
    extend2 = coalesce(?, extend2)
WHERE id = ?
`

type UpdateFileParams struct {
	FileName sql.NullString `json:"file_name"`
	FileSize sql.NullInt64  `json:"file_size"`
	FileAddr sql.NullString `json:"file_addr"`
	Status   sql.NullInt16  `json:"status"`
	Extend   sql.NullInt32  `json:"extend"`
	Extend2  sql.NullString `json:"extend2"`
	ID       int64          `json:"id"`
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFile,
		arg.FileName,
		arg.FileSize,
		arg.FileAddr,
		arg.Status,
		arg.Extend,
		arg.Extend2,
		arg.ID,
	)
}
