// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_user.sql

package db

import (
	"context"
	"database/sql"
)

const createFileUser = `-- name: CreateFileUser :execresult
INSERT INTO file_users (
    username, file_sha1, file_size, filename )
     VALUES (?, ?, ?, ?)
`

type CreateFileUserParams struct {
	Username string `json:"username"`
	FileSha1 string `json:"file_sha1"`
	FileSize int64  `json:"file_size"`
	Filename string `json:"filename"`
}

func (q *Queries) CreateFileUser(ctx context.Context, arg CreateFileUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFileUser,
		arg.Username,
		arg.FileSha1,
		arg.FileSize,
		arg.Filename,
	)
}

const getUserFilesByUsername = `-- name: GetUserFilesByUsername :many
SELECT id, username, file_sha1, file_size, filename, create_at, update_at, status FROM file_users WHERE username = ? AND status = 0 
ORDER BY create_at DESC
limit ? offset ?
`

type GetUserFilesByUsernameParams struct {
	Username string `json:"username"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) GetUserFilesByUsername(ctx context.Context, arg GetUserFilesByUsernameParams) ([]FileUser, error) {
	rows, err := q.db.QueryContext(ctx, getUserFilesByUsername, arg.Username, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileUser{}
	for rows.Next() {
		var i FileUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.FileSha1,
			&i.FileSize,
			&i.Filename,
			&i.CreateAt,
			&i.UpdateAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileUserStatus = `-- name: UpdateFileUserStatus :execresult
UPDATE file_users SET 
status = coalesce(?, status),
filename = coalesce(?, filename),
update_at = now()
WHERE filename = ? AND file_sha1 = ? AND status = ? AND username = ?
`

type UpdateFileUserStatusParams struct {
	Status     sql.NullInt16  `json:"status"`
	Filename   sql.NullString `json:"filename"`
	Filename_2 string         `json:"filename_2"`
	FileSha1   string         `json:"file_sha1"`
	Status_2   int8           `json:"status_2"`
	Username   string         `json:"username"`
}

func (q *Queries) UpdateFileUserStatus(ctx context.Context, arg UpdateFileUserStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateFileUserStatus,
		arg.Status,
		arg.Filename,
		arg.Filename_2,
		arg.FileSha1,
		arg.Status_2,
		arg.Username,
	)
}
