// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type File struct {
	ID int64 `json:"id"`
	// 文件的sha1值
	FileSha1 string `json:"file_sha1"`
	// 文件名
	FileName string `json:"file_name"`
	// 文件大小
	FileSize int64 `json:"file_size"`
	// 文件存储地址
	FileAddr string `json:"file_addr"`
	// 文件状态(0: 正常,1:禁用, 2: 删除)
	Status int8 `json:"status"`
	// 创建时间
	CreateAt time.Time `json:"create_at"`
	// 更新时间
	UpdateAt time.Time `json:"update_at"`
	// 扩展字段
	Extend int32 `json:"extend"`
	// 扩展字段2
	Extend2 sql.NullString `json:"extend2"`
}
