// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetFileById(ctx context.Context, id int64) (File, error)
	GetFileBySha1(ctx context.Context, fileSha1 string) (File, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int64) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
