// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (sql.Result, error)
	GetFileById(ctx context.Context, id int64) (File, error)
	GetFileBySha1(ctx context.Context, fileSha1 string) (File, error)
	UpdateFile(ctx context.Context, arg UpdateFileParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
