// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    username, password,  email, phone    )
     VALUES (?, ?, ?, ?)
`

type CreateUserParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Phone    string `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Phone,
	)
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, password, create_at, update_at, last_login_at, email, phone, email_verified, phone_verified, profile, status FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreateAt,
		&i.UpdateAt,
		&i.LastLoginAt,
		&i.Email,
		&i.Phone,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Profile,
		&i.Status,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, password, create_at, update_at, last_login_at, email, phone, email_verified, phone_verified, profile, status FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreateAt,
		&i.UpdateAt,
		&i.LastLoginAt,
		&i.Email,
		&i.Phone,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Profile,
		&i.Status,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, username, password, create_at, update_at, last_login_at, email, phone, email_verified, phone_verified, profile, status FROM users WHERE phone = ? LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreateAt,
		&i.UpdateAt,
		&i.LastLoginAt,
		&i.Email,
		&i.Phone,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Profile,
		&i.Status,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password, create_at, update_at, last_login_at, email, phone, email_verified, phone_verified, profile, status FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.CreateAt,
		&i.UpdateAt,
		&i.LastLoginAt,
		&i.Email,
		&i.Phone,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Profile,
		&i.Status,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users SET
    username = coalesce(?, username),
    password = coalesce(?, password),
    email = coalesce(?, email),
    phone = coalesce(?, phone),
    email_verified = coalesce(?, email_verified),
    phone_verified = coalesce(?, phone_verified),
    profile = coalesce(?, profile),
    status = coalesce(?, status),
    update_at = CURRENT_TIMESTAMP,
    last_login_at = coalesce(?, last_login_at)
WHERE id = ?
`

type UpdateUserParams struct {
	Username      sql.NullString `json:"username"`
	Password      sql.NullString `json:"password"`
	Email         sql.NullString `json:"email"`
	Phone         sql.NullString `json:"phone"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	PhoneVerified sql.NullBool   `json:"phone_verified"`
	Profile       sql.NullString `json:"profile"`
	Status        sql.NullInt16  `json:"status"`
	LastLoginAt   sql.NullTime   `json:"last_login_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Phone,
		arg.EmailVerified,
		arg.PhoneVerified,
		arg.Profile,
		arg.Status,
		arg.LastLoginAt,
		arg.ID,
	)
}
